---
env:
  browser: true
  es2021: true
  node: true

extends:
  - airbnb
  - plugin:jsx-a11y/recommended
  - prettier

plugins:
  - react
  - jsx-a11y
  - prettier

parser: "@babel/eslint-parser"

settings:
  import/resolver: node

rules:
  no-console: 0
  react/prop-types: 0
  import/extensions: 0
  no-underscore-dangle: [2, { "allow": ["__filename", "__dirname"] }]
  no-param-reassign:
    - error
    - props: true
      ignorePropertyModificationsFor:
        - state
  jsx-a11y/label-has-associated-control: [2, { "controlComponents": ["Field"] }]

  prettier/prettier:
    - error
    - singleQuote: true
      trailingComma: "es5"
      tabWidth: 2

parserOptions:
  ecmaVersion: 12
  sourceType: module
